resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        failureRateThreshold: 50
        ringBufferSizeInClosedState: 5
        waitDurationInOpenState: 30s
        automatic-transition-from-open-to-half-open-enabled: true