server:
  port: 3334
  
spring:
  application:
    name: ProductMS
  cloud:
    consul:
      discovery:
        health-check-url: http://localhost:${server.port}${server.servlet.context-path}/actuator